package com.razorpay.autorecon.model;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

@Entity
@Table(name = "razorpay_settlements")
public class RazorpaySettlement {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String paymentId; // e.g. pay_Nabc123

    private String batchId = "batch_demo";

    private String orderId; // Linked Razorpay order ID e.g. order_Oxyz789

    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal grossAmount; // e.g. 5000.00

    @Column(precision = 10, scale = 2)
    private BigDecimal fee; // e.g. 100.00 (MDR)

    @Column(precision = 10, scale = 2)
    private BigDecimal tax; // e.g. 18.00 (18% GST on Fee)

    @Column(nullable = false, precision = 12, scale = 2)
    private BigDecimal netAmount; // e.g. 4882.00 (gross - fee - tax)

    private String method; // upi, card, netbanking, wallet
    private String settlementId; // setl_S123456
    private String bankUtr; // UTR reference generated by Razorpay payout
    private LocalDateTime paymentCreatedAt;
    private LocalDateTime settledAt;
    private String status; // captured, refunded, failed

    public RazorpaySettlement() {}

    public RazorpaySettlement(String paymentId, String orderId, BigDecimal grossAmount, BigDecimal fee, BigDecimal tax, BigDecimal netAmount, String method, String settlementId, String bankUtr, LocalDateTime paymentCreatedAt, LocalDateTime settledAt, String status) {
        this.paymentId = paymentId;
        this.orderId = orderId;
        this.grossAmount = grossAmount;
        this.fee = fee;
        this.tax = tax;
        this.netAmount = netAmount;
        this.method = method;
        this.settlementId = settlementId;
        this.bankUtr = bankUtr;
        this.paymentCreatedAt = paymentCreatedAt;
        this.settledAt = settledAt;
        this.status = status;
        this.batchId = "batch_demo";
    }

    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public String getPaymentId() { return paymentId; }
    public void setPaymentId(String paymentId) { this.paymentId = paymentId; }

    public String getBatchId() { return batchId; }
    public void setBatchId(String batchId) { this.batchId = batchId; }

    public String getOrderId() { return orderId; }
    public void setOrderId(String orderId) { this.orderId = orderId; }

    public BigDecimal getGrossAmount() { return grossAmount; }
    public void setGrossAmount(BigDecimal grossAmount) { this.grossAmount = grossAmount; }

    public BigDecimal getFee() { return fee; }
    public void setFee(BigDecimal fee) { this.fee = fee; }

    public BigDecimal getTax() { return tax; }
    public void setTax(BigDecimal tax) { this.tax = tax; }

    public BigDecimal getNetAmount() { return netAmount; }
    public void setNetAmount(BigDecimal netAmount) { this.netAmount = netAmount; }

    public String getMethod() { return method; }
    public void setMethod(String method) { this.method = method; }

    public String getSettlementId() { return settlementId; }
    public void setSettlementId(String settlementId) { this.settlementId = settlementId; }

    public String getBankUtr() { return bankUtr; }
    public void setBankUtr(String bankUtr) { this.bankUtr = bankUtr; }

    public LocalDateTime getPaymentCreatedAt() { return paymentCreatedAt; }
    public void setPaymentCreatedAt(LocalDateTime paymentCreatedAt) { this.paymentCreatedAt = paymentCreatedAt; }

    public LocalDateTime getSettledAt() { return settledAt; }
    public void setSettledAt(LocalDateTime settledAt) { this.settledAt = settledAt; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
}
